spring.application.name=springbootweb
#how the will persist shows in phsycial type form
spring.h2.console.enabled=true
#instead of in-memory use file so that data persist even after app restart
spring.datasource.url=jdbc:h2:file:D:/java_springboot/springbootweb/springbootweb/physicalDB
spring.datasource.username=SA
spring.datasource.password=Gandu@123
#by defualt it is setteed =none for in-disk memory by default
spring.jpa.hibernate.ddl-auto=update


