spring.application.name=springbootweb
#how the will persist shows in phsycial type form
#spring.h2.console.enabled=true
#instead of in-memory use file so that data persist even after app restart
#spring.datasource.url=jdbc:h2:file:D:/java_springboot/springbootweb/springbootweb/physicalDB
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=SA
spring.datasource.username=postgres
spring.datasource.password=Gandu@123
#by defualt it is setteed =none for in-disk memory by default
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#security configs
#spring.security.user.name=RAJU
#spring.security.user.password=pass

jwt.secret.key=this_is_my_super_secure_secret_key_which_is_long_enough_123455555555555555555555555555555

#spring.security.oauth2.client.registration.google.client-id=1076234120748-glrkqe8t797qc34tmai4b7g0hhn7ofn6.apps.googleusercontent.com


